language: node_js
node_js:
- node
notifications:
  email: false
  webhooks:
    urls:
      secure: qZhq62T+GV81+tPJr4v+OqkRu3jqAyp1vXu0FFBvmaRDAhC6rzqXa+ZbwHMm/e/ukvHHXu4TvxSVraIIUP/vsqEAT/i9TLB4vq/GcycOBhIzRAu7kOE9GVpBfKKPui5QF5prdRm5raVua8ZMCjqBytAHaaYR+AClcaNcZby66aTSmCAfu29sFKBQ4ZsXq39crmhwiKsmjJSFH6m8rWJmrVHBvErbTOwkv3K187CAp79vGM99q0SVvL5aE+rggWO/OQh1HHyYNdCi0280GrpGFAjZxBUC67BoxoSl9bqSYSat2kJqlavmi1+3OU3U9ClcXyPzGMWoVB6DJNrcynTFTU7GoS63hHmQlPh3fyLgjzl8i+U7LJdI8xZ0zkIz6FI8cEmKRtdQa/+UTbF4+vpr1DowTj8grG5byO3jNs2b66sR2Tcv6tTbb6SECqLQ2gG1WBb0c7gb/RaXLeYKfvgHIsFzxgJd4RYWhutMxJ+gbjkQjfU/ajR+XqbPJt9csGfzJ9dK3045moByCauc6epCBVYMJqVT5xHsyaKnSizS+/YsnKoxbQ6flCG1+BCjAQr8ET+tVBtpxPo8LS9yVbno+OoWNLK5SWIcyFWPnpKN79PaJy3CDHZEIwuxyFp4xC4ToTo2QACPQh3WulSXJfEBjuyYnTUq0UiS1viGdwfqajI=
    on_success: never
    on_failure: always
    on_start: never
    on_cancel: never
    on_error: always
